### ISSUE TITLE
AHB_MIP_match throws false error that outcome variable isn't numeric

### ISSUE THREAD

**Issue by mloop** [almost-matching-exactly/AHB-R-package#1]
I just installed `AHB` from GitHub.

On my dataset `elgan`, I ran the following code:

```
out <- AHB_MIP_match(data = filter(elgan, hypoten == 1), holdout = 0.1, treated_column_name = "vaso", outcome_column_name = "pts_map")
```

Variables:

* `hypoten`: indicator of hypotension
* `vaso`: indicator of vasosuppresor use
* `pts_map`: patient's mean arterial pressure

The error I received was 

```
Error in check_args_MIP(data = df[[1]], holdout = df[[2]], treated_column_name = treated_column_name,  : 
  Outcome variable in data must be numeric value. 
```

I then ran the following code:

```
> is.numeric(elgan$pts_map)
[1] TRUE
```

It appears as if `AHB_MIP_match` falsely thinks that the outcome variable isn't numeric.

**Comment by mloop** [comment]
Removed all missing values, in case `AHB_MIP_match` couldn't handle missing values. Got a new error, which seems counterintuitive:

```
 Error in if (!is.logical(data_treat[l]) && (data_treat[l] != 1 && data_treat[l] !=  : 
  missing value where TRUE/FALSE needed 
```

**Comment by ALEXLANGLANG** [comment]
Hi,

Thank you so much for trying AHB! 
This old version does not have missing data handling method. If there is an NA value in treatment column, if(NA != 1){...} will lead to the error "missing value where TRUE/FALSE needed".

If you change the treated column type as numeric binary or logical and also make sure there is no NA value in treatment column, this issue will be solved I think.

BTW, I just updated the latest version of AHB and it supports missing data handling now. Hope you can try the new version.

Best,
Xian
